"""Reverse spatial lookup — blueprint §5 step 5. STAND-IN for the geometry service.

Blueprint §5: the client sends a raw click coordinate and the backend must turn
it into semantic context ("the user clicked a face generated by obj_base_01")
*before* the Machinist is invoked. Without that step the agent is being asked to
edit something it cannot identify.

The real implementation belongs to Dev B: query build123d for the face nearest
the click and map it back to the history step that generated it. That does not
exist yet, and the Machinist spike cannot wait for it — so this module answers
the same question analytically, from the ledger's own parameters, with no
geometry kernel involved.

What it actually does: gives every live feature an axis-aligned bounding box
derived from its `placement` and `parameters`, then picks the feature whose box
surface is closest to the click point (ties broken toward the later feature,
since later features are cut/added on top of earlier ones and are what the user
sees). It is exact for an axis-aligned box or cylinder sitting alone, and merely
plausible for anything rotated, filleted, or booleaned.

REPLACE THIS with `GeometryService.spatial_query()` when it lands. The contract
already names `SpatialQuery` / `SpatialHit` / `EntityRef`, so the swap is
confined to `resolve_target()` returning the same `TargetResolution`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from cadenza_backend.contracts_bridge import Feature, Ledger


@dataclass(frozen=True)
class TargetResolution:
    """What a click resolved to, plus the sentence handed to the agent."""

    feature_id: str | None
    feature_name: str | None
    distance_mm: float | None
    semantic_context: str
    stub: bool = True

    @property
    def hit(self) -> bool:
        return self.feature_id is not None


def _aabb(feature: Feature) -> tuple[tuple[float, float, float], tuple[float, float, float]] | None:
    """Axis-aligned bounds for a feature, in model space (mm).

    Follows the `Placement` docstring: for box/cylinder the origin is the centre
    of the footprint with z at the BASE; for a hole the origin is where the axis
    meets the face it is cut from and the hole runs along -Z.
    """
    ox, oy, oz = feature.placement.origin
    p = feature.parameters

    if feature.kind == "box":
        hx, hy = p.length / 2.0, p.width / 2.0
        return (ox - hx, oy - hy, oz), (ox + hx, oy + hy, oz + p.height)

    if feature.kind == "cylinder":
        r = p.diameter / 2.0
        return (ox - r, oy - r, oz), (ox + r, oy + r, oz + p.height)

    if feature.kind == "gear":
        # Tip radius. The one derivation this stub does, because a gear has no
        # diameter field to read and an AABB from the pitch circle would sit
        # inside the teeth. Kept as arithmetic rather than an import: this
        # module exists precisely for the venv where cadenza_geometry is absent.
        r = p.module * (p.teeth + 2 + 2 * p.shift) / 2.0
        return (ox - r, oy - r, oz), (ox + r, oy + r, oz + p.height)

    if feature.kind == "hole":
        r = p.diameter / 2.0
        # A through hole has no self-evident depth; use a nominal extent so the
        # distance metric still behaves. Blind holes use their real depth.
        depth = p.depth if (not p.through and p.depth) else r * 4.0
        return (ox - r, oy - r, oz - depth), (ox + r, oy + r, oz)

    return None


def _distance_to_aabb(point: list[float], lo: tuple, hi: tuple) -> float:
    """Euclidean distance from a point to a box. 0 when inside."""
    dx = max(lo[0] - point[0], 0.0, point[0] - hi[0])
    dy = max(lo[1] - point[1], 0.0, point[1] - hi[1])
    dz = max(lo[2] - point[2], 0.0, point[2] - hi[2])
    return math.sqrt(dx * dx + dy * dy + dz * dz)


def resolve_target(ledger: Ledger, point: list[float] | None) -> TargetResolution:
    """Turn a click coordinate into the feature that most likely produced it."""
    if point is None:
        return TargetResolution(
            feature_id=None,
            feature_name=None,
            distance_mm=None,
            semantic_context="The user did not click anything; the instruction applies to the part as a whole.",
        )

    live = [f for f in ledger.features if not f.suppressed]
    if not live:
        return TargetResolution(
            feature_id=None,
            feature_name=None,
            distance_mm=None,
            semantic_context=(
                f"The user clicked at {point}, but the ledger has no features yet, "
                "so nothing can have been clicked."
            ),
        )

    best: tuple[float, Feature] | None = None
    for feature in live:
        bounds = _aabb(feature)
        if bounds is None:
            continue
        distance = _distance_to_aabb(point, *bounds)
        # `<=` breaks ties toward the later feature: later operations sit on top
        # of earlier ones, so they are what the user is looking at.
        if best is None or distance <= best[0]:
            best = (distance, feature)

    if best is None:
        return TargetResolution(
            feature_id=None,
            feature_name=None,
            distance_mm=None,
            semantic_context=f"The user clicked at {point}, but no feature could be resolved.",
        )

    distance, feature = best
    label = feature.name or feature.kind
    inside = "inside" if distance == 0.0 else f"{distance:.2f} mm from"
    return TargetResolution(
        feature_id=feature.id,
        feature_name=feature.name or None,
        distance_mm=distance,
        semantic_context=(
            f"The user clicked at {point} (mm, Z-up), which is {inside} the geometry "
            f"generated by feature `{feature.id}` (\"{label}\", a {feature.kind}). "
            "Treat that feature as the subject of the instruction unless the wording "
            "clearly points elsewhere."
        ),
    )
